### ISSUE TITLE
VirusTotal scan gives a warning about trojan

### ISSUE THREAD

**Issue by iikkart** [RebekkaMa/android-sms-gateway-server#8]
I downloaded the last release and uploaded apk file to VirusTotal. Not sure if it's a false positive. Any comments about this?
![virustotal](https://user-images.githubusercontent.com/41309685/183270684-a0ca7596-462e-4f62-88ec-c06e7e79daeb.png)

**Comment by RebekkaMa** [comment]
Hey!

It’s a false positiv.

The app is used together with the [benkuly/matrix-sms-bridge](https://github.com/benkuly/matrix-sms-bridge) in a doctor’s office to send appointment reminders.

I don’t know what criteria virustotal uses to determine whether an application contains malware or not. Probably it says it contains something because it sends SMS without direct user interaction on the phone because it is triggered from outside through the REST-API. The access is protected by self-determined passwords and usernames.

In addition to that, it can seem suspicious that there is no readme or any documentation. I waited too long to do this and so I need to get back into the code before I can add this. It’s on my list, but unfortunately, as you can see, not my priority.

If you want to be sure it contains no malware, you can build the project yourself.
